### ISSUE TITLE
Light / Dark Mode Component / Library

### ISSUE THREAD

**Issue by SikandarJODD** [ieedan/geist-ui-svelte#103]
We can Use : https://github.com/svecosystem/mode-watcher 
or else can build our own mode watcher and toggle mode using this lib 
Refrence : https://www.shadcn-svelte.com/docs/dark-mode

**Comment by ieedan** [comment]
I actually had no clue shadcn svelte existed

**Comment by ieedan** [comment]
Kinda feel dumb now lmao

**Comment by ieedan** [comment]
Lets add the mode watcher
