### ISSUE TITLE
Typo in the docs

### ISSUE THREAD

**Issue by Angus-Paillaugue** [ieedan/geist-ui-svelte#234]
Hi, I just saw a small error in the components docs. On the `Loading` page, the import statement at the top of the page is actually for the `Divider` and not loading.
<img width="388" alt="image" src="https://github.com/ieedan/geist-ui-svelte/assets/88200698/3693c3f8-3447-4397-9a6f-02cde39422c5">

**Comment by ieedan** [comment]
Thanks for catching this PRs are welcome

**Comment by Angus-Paillaugue** [comment]
Just submitted a pr about this change : [#255](https://github.com/ieedan/geist-ui-svelte/pull/235)

**Comment by ieedan** [comment]
Closed with #255
