### ISSUE TITLE
Tailwind classes not generating after import

### ISSUE THREAD

**Issue by youknowedo** [ieedan/geist-ui-svelte#247]
My Tailwind classes don't generate after importing the components into my page. Followed the [guide](https://geist-ui-svelte.dev/guide/installation).

## Steps to recreate
1. Follow the [guide](https://geist-ui-svelte.dev/guide/installation)
2. In `src/routes/+page.svelte`
```svelte
<script>
	import { Header, LightSwitch } from 'geist-ui-svelte';
</script>

<Header>
	<LightSwitch />
</Header>
```
3. `npm run dev`
4. Inspect element on browser
5. See `<header>` class `border-b`
6. See in `styles` that no css was generated for `border-b`

**Comment by ieedan** [comment]
This is an issue with our setup docs 

Please try editing your tailwind config to include these content paths

```js
/** @type {import('tailwindcss').Config} */
export default {
	content: [
		"./src/**/*.{html,js,svelte,ts}",
		"./node_modules/geist-ui-svelte/**/*.{html,js,svelte,ts}",
	],
	...
};
```
 
I will fix the docs right now

**Comment by ieedan** [comment]
@youknowedo let me know if that works for you
