### ISSUE TITLE
Add 'required' property to labels and form inputs

### ISSUE THREAD

**Issue by ieedan** [ieedan/geist-ui-svelte#258]
This would add the basic functionality as well as including a symbol like '*' to indicate required to the user

**Comment by ieedan** [comment]
I apologize for the vagueness of the original issue.

**Comment by ieedan** [comment]
Basically there should be a property you can add on the `<Input/>` component and `<Label/>` component that would be called `required`.

You could also set `requiredLabel` so that it would show a symbol after the label. Like 'Name*'

Example:
```svelte
<Input required requiredLabel="*">
Name
</Input>
```

**Comment by rabelmervin** [comment]
Hi Madam @ieedan,
I came across this issue, I’m interested in solving this issue. Could you please provide me the location of the project code. This issue will be a great learning opportunity for me .I'm Looking forward to your response. Thank you :)
