### ISSUE TITLE
[TABS] add class prop inside the tabs root element 

### ISSUE THREAD

**Issue by 0x090909** [ieedan/geist-ui-svelte#265]
Add class prop inside the tabs root element, in order to be able to set the padding and border of the whole tabs without messing the underlying border.

**Comment by ieedan** [comment]
PRs are welcome if you'd like to take this on! If not I may have a few minutes later this afternoon.

**Comment by 0x090909** [comment]
Alternatively add possibility to remove border from tabs while keeping the underlying selected item enabeld

**Comment by ieedan** [comment]
> Alternatively add possibility to remove border from tabs while keeping the underlying selected item enabeld

This should already be possible with border=false

https://geist-ui-svelte.dev/components/tabs

![image](https://github.com/user-attachments/assets/b00c17d3-3717-4010-8d3e-95d10781d64e)

**Comment by 0x090909** [comment]
<img width="576" alt="Screenshot 2024-08-10 at 17 40 10" src="https://github.com/user-attachments/assets/90e2e40e-ec61-4db4-9421-93745bc0c577">

Yes but look I want to keep the black under the selected item while keeping the padding on left and right, but I have this artifact where the border collides with the upper level border

**Comment by 0x090909** [comment]
I opened a PR please check it, its a very simple edit, I added className inside the tabs root
