### ISSUE TITLE
Tabs animation does not work when href specified in the props

### ISSUE THREAD

**Issue by 0x090909** [ieedan/geist-ui-svelte#267]
Page is being reloaded and no underline animation of the selected item works

**Comment by ieedan** [comment]
I think this is an HMR issue I think if you do a refresh it should self fix

**Comment by 0x090909** [comment]
strange because if I take out the href prop it works

**Comment by ieedan** [comment]
Oh wait it's not underlined because your current path doesn't match the paths of any provided by href

**Comment by ieedan** [comment]
That's the intended behavior if you make the href something like "/" it will match anything and will therefore show selected

**Comment by 0x090909** [comment]
No wait, the underline works, its the animation of underline that goes from the current selected to the new selected that does not work

**Comment by ieedan** [comment]
Are you using Sveltekit?

**Comment by 0x090909** [comment]
yes

**Comment by ieedan** [comment]
It is probaly not animating because of the navigation but it depends on how you are rendering it I would need a repro to really know.

**Comment by 0x090909** [comment]
maybe works with prerendered true only

**Comment by ieedan** [comment]
If you can create a repro I can take a look at it. Its always worked in the applications I have used it in.

**Comment by 0x090909** [comment]
Okay I recreated the case and it works, my problem then must be because Im using geist ui + shadcn

**Comment by ieedan** [comment]
No it's currently not. I don't think it's colliding I'm currently migrating to shadcn for one of my biggest projects right now and I haven't run into any issues with this. The only overrides this library has is the gray colors.

More than likely I think the project structure is incorrect and you may not have your tabs component in a layout.

If you are looking for a fully shadcn compatible option check out https://geist.shyakadavis.me/.
It's not a component library but it has the same style and APIs (probably better). 

Again I haven't run into any issues while using both in my projects.
