### ISSUE TITLE
[Fixed] Cannot use library not resolving dependency shikiji from Code.svelte

### ISSUE THREAD

**Issue by ieedan** [ieedan/geist-ui-svelte#47]
This issue was fixed in 1.1.0.

Had to move shikiji from dev dependencies to prod dependencies.

**Comment by SikandarJODD** [comment]
Hey i think it should be **SQL**
![image](https://github.com/ieedan/geist-ui-svelte/assets/93428946/44696a30-afe4-44ce-acca-e9935a3dc395)

**Comment by ieedan** [comment]
Highlighted surprisingly well even with the wrong language.

I just posted this issue because up until this morning there was an issue with the shikiji import preventing you from using the library. Hoping anyone who encountered that might see this issue and try again seeing it was fixed.

**Comment by ieedan** [comment]
I'll have to fix the language real quick

**Comment by ieedan** [comment]
Actually it had the right language in the code just not in the docs below

**Comment by SikandarJODD** [comment]
Geist Discord ? for Site showcase and Examples and talks on it ?

**Comment by ieedan** [comment]
> Geist Discord ? for Site showcase and Examples and talks on it ?

Maybe if a community develops right now it's still early don't even have all the docs finished.

I think I have like 6 pages left of docs to complete should be able to knock them out this weekend and then I'll probably work on refining existing components. Some stuff is kinda just there like `Badge` where it was pretty quick and low effort and needs some love.

**Comment by SikandarJODD** [comment]
ok i will wait patiently
