### ISSUE TITLE
Add edit button to guide

### ISSUE THREAD

**Issue by ieedan** [ieedan/geist-ui-svelte#55]
- add edit button to bottom of guide layout like how it is on the components layout

**Comment by akshitchowdhury** [comment]
Sure. I can get it done for you

**Comment by ieedan** [comment]
> Sure. I can get it done for you

Let me know if you still want to work on this I'm gonna knock out a few issues this morning

**Comment by akshitchowdhury** [comment]
Yup I'd be glad to work upon this...

**Comment by SikandarJODD** [comment]
Is there any other way to add css like editing the file system or something 
#
![image](https://github.com/ieedan/geist-ui-svelte/assets/93428946/b462f9e7-5451-4633-9300-4186b1a6c259)
can we add new css file to users file system rather than importing it from node modules

**Comment by ieedan** [comment]
> Yup I'd be glad to work upon this...

Are you going to be able to work on this today otherwise I can just knock it out rq

**Comment by akshitchowdhury** [comment]
Yup @ieedan ..gimme 24r hrs and I'll deliver you the fix..

**Comment by akshitchowdhury** [comment]
Do you want me to create an edit button and add it to the guide folder in the app structure similar to the components one? A little more details regarding this would help 🙂

**Comment by ieedan** [comment]
![image](https://github.com/ieedan/geist-ui-svelte/assets/117548273/41a72887-99d0-442e-b8a6-e3e71160fbc3)

Just add the button that links back to GitHub

**Comment by ieedan** [comment]
To the guide section though
