### ISSUE TITLE
Is there any other way to add css like editing the file system or something

### ISSUE THREAD

**Issue by ieedan** [ieedan/geist-ui-svelte#57]
Is there any other way to add css like editing the file system or something 
#
![image](https://github.com/ieedan/geist-ui-svelte/assets/93428946/b462f9e7-5451-4633-9300-4186b1a6c259)
can we add new css file to users file system rather than importing it from node modules

_Originally posted by @SikandarJODD in https://github.com/ieedan/geist-ui-svelte/issues/55#issuecomment-1890468370_

**Comment by ieedan** [comment]
@SikandarJODD

**Comment by ieedan** [comment]
We could add back the original way which was to include the contents of our css in your app.css, But this was getting kinda klunky and bloated.

This works okay right now when I tested it.

But it would be easier if we could bundle it so the import looks more like

```ts
import "geist-ui-svelte/geist-ui-svelte.css"
```

**Comment by ieedan** [comment]
I haven't done anything like that before any ideas? @SikandarJODD

**Comment by SikandarJODD** [comment]
# Another way of adding tailwind  
```bash 
npx svelte-add@latest tailwindcss
``` 
when you run this command this create layout.svelte and css files in your folder so can we create a css file for user as geist-ui-svelte.css

**Comment by SikandarJODD** [comment]
Also did u remove the Drawer animation on Feildset ? 
![Uploading image.png…]()

**Comment by ieedan** [comment]
It's defaulted to off. I think it's better practice because not everyone wants the animation.

**Comment by ieedan** [comment]
> # Another way of adding tailwind
> ```shell
> npx svelte-add@latest tailwindcss
> ```
> 
> when you run this command this create layout.svelte and css files in your folder so can we create a css file for user as geist-ui-svelte.css Checkout : [Github Repo](https://github.com/svelte-add/tailwindcss)

Can we create our own custom tailwind config with this?

**Comment by ieedan** [comment]
Its a quicker way to tailwind it looks like but not gonna help us fix the css problem

**Comment by ieedan** [comment]
It looks like we need to add the css to a styles directory Im gonna try that and see if it works

**Comment by ieedan** [comment]
Yeah this didn't work

**Comment by ieedan** [comment]
Not really finding an easy way to do this I think the easiest way is still the import from node modules
