### ISSUE TITLE
Handle Text element responsiveness in a better way

### ISSUE THREAD

**Issue by ieedan** [ieedan/geist-ui-svelte#70]
The example from the `Hero` docs uses responsive classes to hide and show either an h2 or h1 and this actually changes the meaning of the tag on the screen which can be misleading and not accessible.

```svelte
<div class="hidden sm:flex">
	<Text type="h1" align="center">geist-ui-svelte</Text>
</div>
<div class="flex sm:hidden">
	<Text type="h2" align="center">geist-ui-svelte</Text>
</div>
```

How should we handle this instead?

My thought is to have default sizing for each tag type that is overrideable with a new attribute maybe `Size` which would directly set the text size. But with this implementation you should still have to show and hide elements for responsiveness.

Alternatively we could use an attribute like `responsive` that when enabled would shrink all of the font sizes by 1 when enabled.

**Comment by SikandarJODD** [comment]
yes we should keep <code>responsive</code> this true i think it would be more better sorry for late reply

**Comment by ieedan** [comment]
I went ahead and merged a PR adding the smSize and mdSize attributes and its added to the docs https://geist-ui-svelte.dev/components/text as the last example I am not sure if I remembered to correct the hero example.

**Comment by ieedan** [comment]
The hero example was not fixed
